function config = legacy_pipeline_config(repositoryRoot)
%LEGACY_PIPELINE_CONFIG Preserve the reviewed raw-data preprocessing behavior.
%
% config = legacy_pipeline_config()
% config = legacy_pipeline_config(repositoryRoot)
%
% Dataset file paths are intentionally empty and must be supplied per flight.
% All preprocessing values are extracted from the former data_extractor.m.

    if nargin < 1 || isempty(repositoryRoot)
        repositoryRoot = fileparts(fileparts(mfilename('fullpath')));
    end
    repositoryRoot = char(string(repositoryRoot));

    config = struct();
    config.schemaVersion = 1;
    config.name = 'legacy_pipeline';
    config.behaviorMode = 'legacy_behavior_preserving';
    config.paths = struct('repositoryRoot', repositoryRoot);
    config.dataset = struct( ...
        'csvFile', '', ...
        'anchorFile', '', ...
        'includeRawTable', true);
    config.preprocessing = struct( ...
        'gyroscopeInterpolationMethod', 'linear', ...
        'gyroscopeExtrapolation', true, ...
        'commonTimeOrigin', 'minimum_first_active_timestamp', ...
        'groundTruthStartRule', 'strictly_after_origin', ...
        'downsampleFactor', 8, ...
        'anchorPairs', [7 0; 0 1; 1 2; 2 3; 3 4; 4 5; 5 6; 6 7], ...
        'groundTruthInterpolationMethod', 'spline', ...
        'generateIdealTdoa', true);
end
